---
# actionlint configuration file, information found below
# https://github.com/rhysd/actionlint/blob/main/docs/config.md
#self-hosted-runner:
  # Labels of self-hosted runner in array of string
  #labels:
  #  - light
  #  - default
  #  - heavy
